language: python
python:
  - "3.5"

addons:
  apt:
    packages:
    - enchant

# command to install dependencies
install:
  - pip install -r requirements/travis.txt

# command to run doc build
script:
  - pwd
  - cd docs-source
  - make gh-html

after_success:
  - git remote rm origin
  - git remote add origin https://marshalc:$GH_TOKEN@github.com/ouh-churchill/diakonia.git
  - git config user.name "Travis Builder"
  - git config user.email "$EMAIL"

  - git add --all
  - git commit -m "[ci skip] Autodoc commit for $TRAVIS_COMMIT."
  - git push -v origin HEAD:master
