language: python
python:
  - "3.5"

addons:
  apt:
    packages:
    - enchant

# command to install dependencies
install:
  - pip install -r requirements/travis.txt
# command to run doc build
script:
#  - travis-sphinx --source=docs-source/ build
  - pwd
  - cd docs-source
  - make gh-html

after_success:
#  - travis-sphinx deploy
  - git remote rm origin
  - git remote add origin https://marshalc:$GH_TOKEN@github.com/ouh-churchill/diakonia.git
  - git config user.name "Travis Builder"
  - git config user.email "$EMAIL"

  - git status
  - git add -A ../
  - git commit -m "[ci skip] Autodoc commit for $COMMIT."

  # -q is very important, otherwise you leak your GH_TOKEN
  - git push -v origin master
